"""Create notifications table

Revision ID: 414fd3ae6ecc
Revises: 59213a263adc
Create Date: 2026-07-07 04:25:53.774855
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '414fd3ae6ecc'
down_revision: Union[str, None] = '59213a263adc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notifications',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('type', sa.Enum('SUCCESS', 'INFO', 'WARNING', 'ERROR', 'SYSTEM', 'AI', 'SECURITY', 'WORKFLOW', name='notification_type_enum'), nullable=False),
    sa.Column('category', sa.Enum('DOCUMENT_PROCESSING', 'AI_INSIGHTS', 'KNOWLEDGE_BASE', 'SEARCH', 'ANALYTICS', 'SYSTEM', 'SECURITY', 'ACCOUNT', 'ORGANIZATION', 'PWA', name='notification_category_enum'), nullable=False),
    sa.Column('priority', sa.Enum('LOW', 'NORMAL', 'HIGH', 'URGENT', name='notification_priority_enum'), nullable=False),
    sa.Column('action_url', sa.String(length=1024), nullable=True),
    sa.Column('action_label', sa.String(length=100), nullable=True),
    sa.Column('icon', sa.String(length=100), nullable=True),
    sa.Column('metadata_json', sa.JSON(), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_notifications_category', 'notifications', ['category'], unique=False)
    op.create_index('ix_notifications_created_at', 'notifications', ['created_at'], unique=False)
    op.create_index('ix_notifications_is_read', 'notifications', ['is_read'], unique=False)
    op.create_index('ix_notifications_user_id', 'notifications', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_notifications_user_id', table_name='notifications')
    op.drop_index('ix_notifications_is_read', table_name='notifications')
    op.drop_index('ix_notifications_created_at', table_name='notifications')
    op.drop_index('ix_notifications_category', table_name='notifications')
    op.drop_table('notifications')
    # ### end Alembic commands ###
