"""Add intelligence and KG models

Revision ID: 59213a263adc
Revises: 8c0bbc0b0f16
Create Date: 2026-07-06 15:02:23.333143
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '59213a263adc'
down_revision: Union[str, None] = '8c0bbc0b0f16'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('knowledge_clusters',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('color', sa.String(length=50), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_clusters_id'), 'knowledge_clusters', ['id'], unique=False)
    op.create_table('workflow_templates',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('trigger_type', sa.String(length=100), nullable=False),
    sa.Column('workflow_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workflow_templates_id'), 'workflow_templates', ['id'], unique=False)
    op.create_table('knowledge_nodes',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('node_type', sa.String(length=100), nullable=False),
    sa.Column('summary', sa.String(length=2000), nullable=True),
    sa.Column('embedding_id', sa.String(length=255), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_nodes_document_id'), 'knowledge_nodes', ['document_id'], unique=False)
    op.create_index(op.f('ix_knowledge_nodes_id'), 'knowledge_nodes', ['id'], unique=False)
    op.create_index(op.f('ix_knowledge_nodes_node_type'), 'knowledge_nodes', ['node_type'], unique=False)
    op.create_index(op.f('ix_knowledge_nodes_title'), 'knowledge_nodes', ['title'], unique=False)
    op.create_table('knowledge_edges',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('source_node_id', sa.String(length=36), nullable=False),
    sa.Column('target_node_id', sa.String(length=36), nullable=False),
    sa.Column('relationship_type', sa.String(length=255), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_node_id'], ['knowledge_nodes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_node_id'], ['knowledge_nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_knowledge_edges_id'), 'knowledge_edges', ['id'], unique=False)
    op.create_index(op.f('ix_knowledge_edges_relationship_type'), 'knowledge_edges', ['relationship_type'], unique=False)
    op.create_index(op.f('ix_knowledge_edges_source_node_id'), 'knowledge_edges', ['source_node_id'], unique=False)
    op.create_index(op.f('ix_knowledge_edges_target_node_id'), 'knowledge_edges', ['target_node_id'], unique=False)
    op.create_table('node_clusters',
    sa.Column('node_id', sa.String(length=36), nullable=False),
    sa.Column('cluster_id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['knowledge_clusters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['node_id'], ['knowledge_nodes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('node_id', 'cluster_id')
    )
    op.create_table('recommendations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=False),
    sa.Column('severity', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=True),
    sa.Column('knowledge_node_id', sa.String(length=36), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['knowledge_node_id'], ['knowledge_nodes.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_recommendations_document_id'), 'recommendations', ['document_id'], unique=False)
    op.create_index(op.f('ix_recommendations_id'), 'recommendations', ['id'], unique=False)
    op.create_index(op.f('ix_recommendations_knowledge_node_id'), 'recommendations', ['knowledge_node_id'], unique=False)
    op.create_index(op.f('ix_recommendations_type'), 'recommendations', ['type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_recommendations_type'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_knowledge_node_id'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_id'), table_name='recommendations')
    op.drop_index(op.f('ix_recommendations_document_id'), table_name='recommendations')
    op.drop_table('recommendations')
    op.drop_table('node_clusters')
    op.drop_index(op.f('ix_knowledge_edges_target_node_id'), table_name='knowledge_edges')
    op.drop_index(op.f('ix_knowledge_edges_source_node_id'), table_name='knowledge_edges')
    op.drop_index(op.f('ix_knowledge_edges_relationship_type'), table_name='knowledge_edges')
    op.drop_index(op.f('ix_knowledge_edges_id'), table_name='knowledge_edges')
    op.drop_table('knowledge_edges')
    op.drop_index(op.f('ix_knowledge_nodes_title'), table_name='knowledge_nodes')
    op.drop_index(op.f('ix_knowledge_nodes_node_type'), table_name='knowledge_nodes')
    op.drop_index(op.f('ix_knowledge_nodes_id'), table_name='knowledge_nodes')
    op.drop_index(op.f('ix_knowledge_nodes_document_id'), table_name='knowledge_nodes')
    op.drop_table('knowledge_nodes')
    op.drop_index(op.f('ix_workflow_templates_id'), table_name='workflow_templates')
    op.drop_table('workflow_templates')
    op.drop_index(op.f('ix_knowledge_clusters_id'), table_name='knowledge_clusters')
    op.drop_table('knowledge_clusters')
    # ### end Alembic commands ###
