"""add_ai_knowledge_models

Revision ID: 685d392c2c51
Revises: e71ad3aa6454
Create Date: 2026-07-17 06:21:44.669566
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '685d392c2c51'
down_revision: Union[str, None] = 'e71ad3aa6454'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('search_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('query', sa.String(length=1000), nullable=False),
    sa.Column('search_type', sa.String(length=50), nullable=False),
    sa.Column('results_count', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('is_successful', sa.Boolean(), nullable=False),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_search_logs_created_at'), 'search_logs', ['created_at'], unique=False)
    op.create_index(op.f('ix_search_logs_id'), 'search_logs', ['id'], unique=False)
    op.create_index(op.f('ix_search_logs_query'), 'search_logs', ['query'], unique=False)
    op.create_index(op.f('ix_search_logs_user_id'), 'search_logs', ['user_id'], unique=False)
    op.create_table('document_intelligence',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('executive_summary', sa.String(), nullable=True),
    sa.Column('topics', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('keywords', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('entities', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('action_items', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('risks', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('faqs', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('suggested_questions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_intelligence_document_id'), 'document_intelligence', ['document_id'], unique=True)
    op.create_index(op.f('ix_document_intelligence_id'), 'document_intelligence', ['id'], unique=False)
    op.drop_table('node_clusters')
    op.drop_index('ix_knowledge_clusters_id', table_name='knowledge_clusters')
    op.drop_table('knowledge_clusters')
    op.add_column('documents', sa.Column('embedding_model', sa.String(length=200), nullable=True))
    op.add_column('documents', sa.Column('embedding_dimension', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('vector_count', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('indexed_at', sa.String(length=50), nullable=True))
    op.add_column('documents', sa.Column('index_status', sa.String(length=50), nullable=True))
    op.add_column('knowledge_nodes', sa.Column('workspace_id', sa.String(length=36), nullable=True))
    op.add_column('knowledge_nodes', sa.Column('type', sa.String(length=100), nullable=False))
    op.add_column('knowledge_nodes', sa.Column('label', sa.String(length=500), nullable=False))
    op.drop_index('ix_knowledge_nodes_document_id', table_name='knowledge_nodes')
    op.drop_index('ix_knowledge_nodes_node_type', table_name='knowledge_nodes')
    op.drop_index('ix_knowledge_nodes_title', table_name='knowledge_nodes')
    op.create_index(op.f('ix_knowledge_nodes_label'), 'knowledge_nodes', ['label'], unique=False)
    op.create_index(op.f('ix_knowledge_nodes_type'), 'knowledge_nodes', ['type'], unique=False)
    op.create_index(op.f('ix_knowledge_nodes_workspace_id'), 'knowledge_nodes', ['workspace_id'], unique=False)
    op.drop_constraint('knowledge_nodes_document_id_fkey', 'knowledge_nodes', type_='foreignkey')
    op.drop_column('knowledge_nodes', 'node_type')
    op.drop_column('knowledge_nodes', 'document_id')
    op.drop_column('knowledge_nodes', 'title')
    op.drop_column('knowledge_nodes', 'summary')
    op.add_column('messages', sa.Column('context_json', sa.JSON(), nullable=True))
    op.execute("ALTER TYPE messagerole RENAME TO messagerole_old")
    op.execute("CREATE TYPE role AS ENUM ('system', 'user', 'assistant')")
    op.execute("ALTER TABLE messages ALTER COLUMN role TYPE role USING lower(role::text)::role")
    op.execute("DROP TYPE messagerole_old")
    op.drop_column('messages', 'model_used')
    op.drop_column('messages', 'retrieved_chunks')
    op.drop_column('messages', 'citations')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('citations', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('messages', sa.Column('retrieved_chunks', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('messages', sa.Column('model_used', sa.VARCHAR(length=100), autoincrement=False, nullable=True))
    op.execute("ALTER TYPE role RENAME TO role_old")
    op.execute("CREATE TYPE messagerole AS ENUM ('USER', 'ASSISTANT', 'SYSTEM')")
    op.execute("ALTER TABLE messages ALTER COLUMN role TYPE messagerole USING upper(role::text)::messagerole")
    op.execute("DROP TYPE role_old")
    op.drop_column('messages', 'context_json')
    op.add_column('knowledge_nodes', sa.Column('summary', sa.VARCHAR(length=2000), autoincrement=False, nullable=True))
    op.add_column('knowledge_nodes', sa.Column('title', sa.VARCHAR(length=500), autoincrement=False, nullable=False))
    op.add_column('knowledge_nodes', sa.Column('document_id', sa.VARCHAR(length=36), autoincrement=False, nullable=True))
    op.add_column('knowledge_nodes', sa.Column('node_type', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.create_foreign_key('knowledge_nodes_document_id_fkey', 'knowledge_nodes', 'documents', ['document_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_knowledge_nodes_workspace_id'), table_name='knowledge_nodes')
    op.drop_index(op.f('ix_knowledge_nodes_type'), table_name='knowledge_nodes')
    op.drop_index(op.f('ix_knowledge_nodes_label'), table_name='knowledge_nodes')
    op.create_index('ix_knowledge_nodes_title', 'knowledge_nodes', ['title'], unique=False)
    op.create_index('ix_knowledge_nodes_node_type', 'knowledge_nodes', ['node_type'], unique=False)
    op.create_index('ix_knowledge_nodes_document_id', 'knowledge_nodes', ['document_id'], unique=False)
    op.drop_column('knowledge_nodes', 'label')
    op.drop_column('knowledge_nodes', 'type')
    op.drop_column('knowledge_nodes', 'workspace_id')
    op.drop_column('documents', 'index_status')
    op.drop_column('documents', 'indexed_at')
    op.drop_column('documents', 'vector_count')
    op.drop_column('documents', 'embedding_dimension')
    op.drop_column('documents', 'embedding_model')
    op.create_table('knowledge_clusters',
    sa.Column('id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(length=1000), autoincrement=False, nullable=True),
    sa.Column('color', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='knowledge_clusters_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index('ix_knowledge_clusters_id', 'knowledge_clusters', ['id'], unique=False)
    op.create_table('node_clusters',
    sa.Column('node_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.Column('cluster_id', sa.VARCHAR(length=36), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['knowledge_clusters.id'], name='node_clusters_cluster_id_fkey', ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['node_id'], ['knowledge_nodes.id'], name='node_clusters_node_id_fkey', ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('node_id', 'cluster_id', name='node_clusters_pkey')
    )
    op.drop_index(op.f('ix_document_intelligence_id'), table_name='document_intelligence')
    op.drop_index(op.f('ix_document_intelligence_document_id'), table_name='document_intelligence')
    op.drop_table('document_intelligence')
    op.drop_index(op.f('ix_search_logs_user_id'), table_name='search_logs')
    op.drop_index(op.f('ix_search_logs_query'), table_name='search_logs')
    op.drop_index(op.f('ix_search_logs_id'), table_name='search_logs')
    op.drop_index(op.f('ix_search_logs_created_at'), table_name='search_logs')
    op.drop_table('search_logs')
    # ### end Alembic commands ###
