"""add_rate_limit_logs_and_roles

Revision ID: e86a5e575353
Revises: 7d406ec76e6e
Create Date: 2026-07-07 05:26:42.997315
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'e86a5e575353'
down_revision: Union[str, None] = '7d406ec76e6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rate_limit_logs',
    sa.Column('user_id', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=100), nullable=False),
    sa.Column('endpoint', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('limit_value', sa.Integer(), nullable=False),
    sa.Column('remaining', sa.Integer(), nullable=False),
    sa.Column('violation_type', sa.String(length=100), nullable=False),
    sa.Column('security_score', sa.Float(), nullable=True),
    sa.Column('decision', sa.String(length=50), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rate_limit_logs_endpoint'), 'rate_limit_logs', ['endpoint'], unique=False)
    op.create_index(op.f('ix_rate_limit_logs_id'), 'rate_limit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_rate_limit_logs_ip_address'), 'rate_limit_logs', ['ip_address'], unique=False)
    op.create_index('ix_rate_limit_logs_ip_time', 'rate_limit_logs', ['ip_address', 'created_at'], unique=False)
    op.create_index(op.f('ix_rate_limit_logs_user_id'), 'rate_limit_logs', ['user_id'], unique=False)
    op.create_index('ix_rate_limit_logs_user_time', 'rate_limit_logs', ['user_id', 'created_at'], unique=False)
    op.execute("ALTER TYPE userrole ADD VALUE IF NOT EXISTS 'super_admin'")
    op.execute("ALTER TYPE userrole ADD VALUE IF NOT EXISTS 'viewer'")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass # Cannot safely downgrade ENUM values in PostgreSQL
    op.drop_index('ix_rate_limit_logs_user_time', table_name='rate_limit_logs')
    op.drop_index(op.f('ix_rate_limit_logs_user_id'), table_name='rate_limit_logs')
    op.drop_index('ix_rate_limit_logs_ip_time', table_name='rate_limit_logs')
    op.drop_index(op.f('ix_rate_limit_logs_ip_address'), table_name='rate_limit_logs')
    op.drop_index(op.f('ix_rate_limit_logs_id'), table_name='rate_limit_logs')
    op.drop_index(op.f('ix_rate_limit_logs_endpoint'), table_name='rate_limit_logs')
    op.drop_table('rate_limit_logs')
    # ### end Alembic commands ###
