"""Add Workspace and Enterprise Security Models

Revision ID: fc4ab3e2c198
Revises: 685d392c2c51
Create Date: 2026-07-17 06:54:53.789665
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'fc4ab3e2c198'
down_revision: Union[str, None] = '685d392c2c51'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('workspaces',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=True),
    sa.Column('document_policy', sa.JSON(), nullable=True),
    sa.Column('ai_policy', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_by', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workspaces_deleted_at'), 'workspaces', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_workspaces_id'), 'workspaces', ['id'], unique=False)
    op.create_table('workspace_members',
    sa.Column('workspace_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.Enum('admin', 'manager', 'engineer', 'viewer', name='workspacerole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workspace_id'], ['workspaces.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_workspace_members_id'), 'workspace_members', ['id'], unique=False)
    op.create_index(op.f('ix_workspace_members_user_id'), 'workspace_members', ['user_id'], unique=False)
    op.create_index(op.f('ix_workspace_members_workspace_id'), 'workspace_members', ['workspace_id'], unique=False)
    op.add_column('audit_logs', sa.Column('session_id', sa.String(length=255), nullable=True))
    op.add_column('audit_logs', sa.Column('status', sa.String(length=50), nullable=True))
    op.add_column('audit_logs', sa.Column('severity', sa.String(length=50), nullable=True))
    op.add_column('audit_logs', sa.Column('metadata_json', sa.JSON(), nullable=True))
    op.add_column('audit_logs', sa.Column('workspace_id', sa.String(length=36), nullable=True))
    op.create_index(op.f('ix_audit_logs_session_id'), 'audit_logs', ['session_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_status'), 'audit_logs', ['status'], unique=False)
    op.create_index(op.f('ix_audit_logs_workspace_id'), 'audit_logs', ['workspace_id'], unique=False)
    op.create_foreign_key(None, 'audit_logs', 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')
    op.drop_column('audit_logs', 'new_value')
    op.drop_column('audit_logs', 'old_value')
    op.drop_column('audit_logs', 'user_snapshot')
    op.add_column('conversations', sa.Column('workspace_id', sa.String(length=36), nullable=True))
    op.add_column('conversations', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('conversations', sa.Column('deleted_by', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_conversations_deleted_at'), 'conversations', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_conversations_workspace_id'), 'conversations', ['workspace_id'], unique=False)
    op.create_foreign_key(None, 'conversations', 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')
    op.add_column('document_intelligence', sa.Column('workspace_id', sa.String(length=36), nullable=True))
    op.add_column('document_intelligence', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('document_intelligence', sa.Column('deleted_by', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_document_intelligence_deleted_at'), 'document_intelligence', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_document_intelligence_workspace_id'), 'document_intelligence', ['workspace_id'], unique=False)
    op.create_foreign_key(None, 'document_intelligence', 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')
    op.add_column('documents', sa.Column('workspace_id', sa.String(length=36), nullable=True))
    op.add_column('documents', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('documents', sa.Column('deleted_by', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_documents_deleted_at'), 'documents', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_documents_workspace_id'), 'documents', ['workspace_id'], unique=False)
    op.create_foreign_key(None, 'documents', 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')
    op.add_column('knowledge_edges', sa.Column('workspace_id', sa.String(length=36), nullable=True))
    op.add_column('knowledge_edges', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('knowledge_edges', sa.Column('deleted_by', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_knowledge_edges_deleted_at'), 'knowledge_edges', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_knowledge_edges_workspace_id'), 'knowledge_edges', ['workspace_id'], unique=False)
    op.create_foreign_key(None, 'knowledge_edges', 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')
    op.add_column('knowledge_nodes', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('knowledge_nodes', sa.Column('deleted_by', sa.String(length=255), nullable=True))

    op.create_index(op.f('ix_knowledge_nodes_deleted_at'), 'knowledge_nodes', ['deleted_at'], unique=False)
    op.create_foreign_key(None, 'knowledge_nodes', 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')
    op.add_column('messages', sa.Column('workspace_id', sa.String(length=36), nullable=True))
    op.add_column('messages', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('messages', sa.Column('deleted_by', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_messages_deleted_at'), 'messages', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_messages_workspace_id'), 'messages', ['workspace_id'], unique=False)
    op.create_foreign_key(None, 'messages', 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')
    op.add_column('search_logs', sa.Column('workspace_id', sa.String(length=36), nullable=True))
    op.add_column('search_logs', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('search_logs', sa.Column('deleted_by', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_search_logs_deleted_at'), 'search_logs', ['deleted_at'], unique=False)
    op.create_index(op.f('ix_search_logs_workspace_id'), 'search_logs', ['workspace_id'], unique=False)
    op.create_foreign_key(None, 'search_logs', 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')
    op.add_column('users', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('users', sa.Column('deleted_by', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_users_deleted_at'), 'users', ['deleted_at'], unique=False)

    # --- DATA MIGRATION ---
    bind = op.get_bind()
    import uuid, datetime
    default_workspace_id = str(uuid.uuid4())
    now = datetime.datetime.now(datetime.timezone.utc)
    
    # 1. Create Default Workspace
    bind.execute(sa.text(
        "INSERT INTO workspaces (id, name, is_active, created_at, updated_at) "
        "VALUES (:id, 'Default Workspace', true, :now, :now)"
    ), {"id": default_workspace_id, "now": now})
    
    # 2. Assign all existing users to Default Workspace
    bind.execute(sa.text(
        "INSERT INTO workspace_members (id, workspace_id, user_id, role, is_active, created_at, updated_at) "
        "SELECT gen_random_uuid()::varchar(36), :wid, id, 'admin', true, :now, :now FROM users"
    ), {"wid": default_workspace_id, "now": now})

    # 3. Backfill workspace_id for all tables
    for table in ['audit_logs', 'conversations', 'document_intelligence', 'documents', 'knowledge_edges', 'knowledge_nodes', 'messages', 'search_logs']:
        bind.execute(sa.text(f"UPDATE {table} SET workspace_id = :wid"), {"wid": default_workspace_id})
        op.alter_column(table, 'workspace_id', existing_type=sa.String(length=36), nullable=False)
        
    # 4. Backfill status and severity for audit_logs
    bind.execute(sa.text("UPDATE audit_logs SET status = 'SUCCESS', severity = 'INFO'"))
    op.alter_column('audit_logs', 'status', existing_type=sa.String(length=50), nullable=False)
    op.alter_column('audit_logs', 'severity', existing_type=sa.String(length=50), nullable=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_deleted_at'), table_name='users')
    op.drop_column('users', 'deleted_by')
    op.drop_column('users', 'deleted_at')
    op.drop_constraint(None, 'search_logs', type_='foreignkey')
    op.drop_index(op.f('ix_search_logs_workspace_id'), table_name='search_logs')
    op.drop_index(op.f('ix_search_logs_deleted_at'), table_name='search_logs')
    op.drop_column('search_logs', 'deleted_by')
    op.drop_column('search_logs', 'deleted_at')
    op.drop_column('search_logs', 'workspace_id')
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_index(op.f('ix_messages_workspace_id'), table_name='messages')
    op.drop_index(op.f('ix_messages_deleted_at'), table_name='messages')
    op.drop_column('messages', 'deleted_by')
    op.drop_column('messages', 'deleted_at')
    op.drop_column('messages', 'workspace_id')
    op.drop_constraint(None, 'knowledge_nodes', type_='foreignkey')
    op.drop_index(op.f('ix_knowledge_nodes_deleted_at'), table_name='knowledge_nodes')
    op.alter_column('knowledge_nodes', 'workspace_id',
               existing_type=sa.VARCHAR(length=36),
               nullable=True)
    op.drop_column('knowledge_nodes', 'deleted_by')
    op.drop_column('knowledge_nodes', 'deleted_at')
    op.drop_constraint(None, 'knowledge_edges', type_='foreignkey')
    op.drop_index(op.f('ix_knowledge_edges_workspace_id'), table_name='knowledge_edges')
    op.drop_index(op.f('ix_knowledge_edges_deleted_at'), table_name='knowledge_edges')
    op.drop_column('knowledge_edges', 'deleted_by')
    op.drop_column('knowledge_edges', 'deleted_at')
    op.drop_column('knowledge_edges', 'workspace_id')
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_index(op.f('ix_documents_workspace_id'), table_name='documents')
    op.drop_index(op.f('ix_documents_deleted_at'), table_name='documents')
    op.drop_column('documents', 'deleted_by')
    op.drop_column('documents', 'deleted_at')
    op.drop_column('documents', 'workspace_id')
    op.drop_constraint(None, 'document_intelligence', type_='foreignkey')
    op.drop_index(op.f('ix_document_intelligence_workspace_id'), table_name='document_intelligence')
    op.drop_index(op.f('ix_document_intelligence_deleted_at'), table_name='document_intelligence')
    op.drop_column('document_intelligence', 'deleted_by')
    op.drop_column('document_intelligence', 'deleted_at')
    op.drop_column('document_intelligence', 'workspace_id')
    op.drop_constraint(None, 'conversations', type_='foreignkey')
    op.drop_index(op.f('ix_conversations_workspace_id'), table_name='conversations')
    op.drop_index(op.f('ix_conversations_deleted_at'), table_name='conversations')
    op.drop_column('conversations', 'deleted_by')
    op.drop_column('conversations', 'deleted_at')
    op.drop_column('conversations', 'workspace_id')
    op.add_column('audit_logs', sa.Column('user_snapshot', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('audit_logs', sa.Column('old_value', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('audit_logs', sa.Column('new_value', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.drop_index(op.f('ix_audit_logs_workspace_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_status'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_session_id'), table_name='audit_logs')
    op.drop_column('audit_logs', 'workspace_id')
    op.drop_column('audit_logs', 'metadata_json')
    op.drop_column('audit_logs', 'severity')
    op.drop_column('audit_logs', 'status')
    op.drop_column('audit_logs', 'session_id')
    op.drop_index(op.f('ix_workspace_members_workspace_id'), table_name='workspace_members')
    op.drop_index(op.f('ix_workspace_members_user_id'), table_name='workspace_members')
    op.drop_index(op.f('ix_workspace_members_id'), table_name='workspace_members')
    op.drop_table('workspace_members')
    op.drop_index(op.f('ix_workspaces_id'), table_name='workspaces')
    op.drop_index(op.f('ix_workspaces_deleted_at'), table_name='workspaces')
    op.drop_table('workspaces')
    # ### end Alembic commands ###
